config/routes.rb
Rails.application.routes.draw do
  # get 'activities/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'activities#index'
  get 'activities/new', to: 'activities#new', as: 'new_activity'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/activities/index.html.erb
<h3>What do you want to do?</h3>
<%= link_to "New Activity", new_activity_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Organizr</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "Blog App", root_path, class: "navbar-brand" %>
        </div>
        <div class="navbar-collapse collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="active"><%= link_to "Authors", "#" %></li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container-fluid">
      <% flash.each do |name, msg| %>
        <div class='alert alert-<%="#{name}" %>'>
          <a href='#' class="close" data-dismiss="alert" &#215;></a>
          <%= content_tag :div, msg, :id => "flash_#{name}"
            if msg.is_a?(String) %>
        </div>
      <% end %>

      <div class="row">

        <div class="col-md-10 col-md-offset-1">
          <div class="col-md-8">
            <%= yield %>
          </div>
        </div>

        <div class="col-md-4">
          <%= yield :sidebar %>
        </div>

      </div>
    </div>
  </body>
</html>